### ISSUE TITLE
코드 수정 요청 사항

### ISSUE THREAD

**Issue by snoopspy** [Kogoon/pcap-test#1]
https://github.com/Kogoon/pcap-test/commit/6e1ac874c85a3f99519216ca3394767ca4c3de3d#r38443969

**Comment by Kogoon** [comment]
Done in https://github.com/Kogoon/pcap-test/commit/62bbcb77d0bf12338d3183b422a0fac841ead193

**Comment by snoopspy** [comment]
수고하셨습니다.
